import {useEffect, useRef, useState} from 'react';
import {ArrowUpRight, X, ChevronLeft, ChevronRight, Instagram, Mail, Phone, Search} from 'lucide-react';
import {doc, onSnapshot} from 'firebase/firestore';
import {portfolioDb as db} from './portfolioFirestore';
import initial from './portfolio.json';
import './portfolio.css';

type Project={id:string;title:string;year:string;genre:string;location?:string;role:string;description?:string;images:string[]};
type Portfolio=typeof initial;
const genres=[['All','전체'],['Theatre','연극'],['Musical','뮤지컬'],['Dance','무용'],['Other','그 외']];
const genreLabel=(genre:string)=>genres.find(([g])=>g.toLowerCase()===genre.toLowerCase())?.[1]||'그 외';
const matchesGenre=(project:Project,genre:string)=>genre==='All'||(genre==='Other'?!['theatre','musical','dance'].includes(project.genre.toLowerCase()):project.genre.toLowerCase()===genre.toLowerCase());
function photoUrl(url:string){const match=url.match(/drive\.google\.com\/(?:file\/d\/([^/?]+)|(?:open|uc)\?[^#]*?id=([^&#]+))/);return match?`https://lh3.googleusercontent.com/d/${match[1]||match[2]}`:url;}
function Picture({src,alt}:{src?:string;alt:string}){const [broken,setBroken]=useState(false);useEffect(()=>setBroken(false),[src]);return src&&!broken?<img src={photoUrl(src)} alt={alt} loading="lazy" referrerPolicy="no-referrer" onError={()=>setBroken(true)}/>:<div className="no-photo"><span>不汗黨</span><small>{src?'사진을 불러올 수 없습니다':'공연 이력'}</small></div>;}
export default function PortfolioApp(){
 const [data,setData]=useState<Portfolio>(initial),[genre,setGenre]=useState('All'),[query,setQuery]=useState(''),[selected,setSelected]=useState<Project|null>(null),[imageIndex,setImageIndex]=useState(0),[notice,setNotice]=useState('');
 const dialog=useRef<HTMLDialogElement>(null),lastFocus=useRef<HTMLElement|null>(null);
 useEffect(()=>onSnapshot(doc(db,'portfolios','main'),snapshot=>{if(snapshot.exists()){const remote=snapshot.data();if(Array.isArray(remote.projects))setData({...initial,...remote,about:{...initial.about,...remote.about},contact:{...initial.contact,...remote.contact}} as Portfolio);}},()=>setNotice('현재 저장된 포트폴리오를 표시하고 있습니다. 연결이 복구되면 최신 내용으로 갱신됩니다.')),[]);
 useEffect(()=>{if(selected){dialog.current?.showModal();document.body.style.overflow='hidden';}else{dialog.current?.close();document.body.style.overflow='';lastFocus.current?.focus();}return()=>{document.body.style.overflow='';};},[selected]);
 const projects=data.projects.map(p=>({...p,year:String(p.year||'연도 미정'),genre:p.genre||'',images:(p.images||[]).filter(src=>typeof src==='string'&&src.trim())})).sort((a,b)=>Number(b.year)-Number(a.year)) as Project[];
 const shown=projects.filter(p=>matchesGenre(p,genre)&&`${p.title} ${p.year} ${p.location||''}`.toLowerCase().includes(query.toLowerCase()));
 const years=[...new Set(shown.map(p=>p.year))];
 const open=(p:Project)=>{lastFocus.current=document.activeElement as HTMLElement;setImageIndex(0);setSelected(p);};
 const changeImage=(step:number)=>{if(selected?.images.length)setImageIndex(i=>(i+step+selected.images.length)%selected.images.length);};
 return <><header><a className="brand" href="#home">불한당<span>LIGHTING DESIGN STUDIO</span></a><nav aria-label="주 메뉴"><a href="#work">WORK</a><a href="#about">ABOUT</a><a href="#contact">CONTACT</a></nav>{import.meta.env.DEV?<a className="local-editor-link" href="/?editor=1">편집</a>:<span className="header-note">SEOUL, KR</span>}</header>
 <main><section className="hero" id="home"><div className="hero-light"/><div className="hero-top"><span>LIGHTING DESIGN · KIM JAE JUN</span><span>빛으로 만드는, 극의 공간</span></div><div className="hero-title">{data.logoUrl?<img src={photoUrl(data.logoUrl)} alt="불한당 스튜디오 원본 로고" referrerPolicy="no-referrer"/>:<h1>불한당</h1>}</div><div className="hero-bottom"><div><p className="eyebrow">BULHANDANG STUDIO</p><p className="hero-quote">극의 공간 안에<br/>있는 것처럼.</p></div><div className="hero-description"><p>보이지 않는 곳에서 빛을 비추어<br/>무대의 공기를 바꾸는 조명 디자인.</p><a href="#work" className="text-link">작품 살펴보기 <span>↓</span></a></div></div></section>
 <section id="work" className="work section"><div className="section-heading"><div><p className="eyebrow">01 / SELECTED WORK & ARCHIVE</p><h2>빛이 머물렀던 순간들<span className="count">{projects.length}</span></h2></div><p className="section-sub">무대 위의 이야기,<br/>그 안의 빛을 기록합니다.</p></div><div className="work-toolbar"><div className="filters" aria-label="장르 필터">{genres.map(([key,label])=><button key={key} aria-pressed={genre===key} className={genre===key?'active':''} onClick={()=>setGenre(key)}>{label}<small>{projects.filter(p=>matchesGenre(p,key)).length}</small></button>)}</div><label className="search"><Search size={16}/><input aria-label="작품 검색" placeholder="작품명 · 연도 검색" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
 <div className="year-archive" key={`${genre}:${query}`}><span className="sr-only" role="status">{shown.length}개 작품 · {years.length}개 연도</span>{years.map(year=>{const works=shown.filter(p=>p.year===year),photos=works.filter(p=>p.images.length),records=works.filter(p=>!p.images.length);return <details className="year-group" key={year} open><summary><span className="year-label">{year}<small>{works.length} WORKS</small></span><span className="year-toggle" aria-hidden="true"/></summary><div className="year-content">{!!photos.length&&<div className="year-photo-grid">{photos.map(p=><button className="photo-project" key={p.id} onClick={()=>open(p)}><div className="project-image"><Picture src={p.images[0]} alt={p.title}/><span className="project-open">작품 보기 <ArrowUpRight size={17}/></span></div><div className="photo-project-copy"><div className="project-meta"><span>{genreLabel(p.genre)} / LIGHTING DESIGN</span><span>{p.images.length} PHOTOS</span></div><h3>{p.title}</h3><p>{p.location||p.role}</p></div></button>)}</div>}{!!records.length&&<div className="year-records">{records.map(p=><button className="record-project" key={p.id} onClick={()=>open(p)}><span className="record-genre">{genreLabel(p.genre)}</span><span className="record-copy"><strong>{p.title}</strong><span>{p.location||p.role}</span></span><span className="record-status">공연 이력</span></button>)}</div>}</div></details>;})}</div>
 {!shown.length&&<div className="empty">검색된 작품이 없습니다.<button onClick={()=>{setQuery('');setGenre('All');}}>전체 작품 보기</button></div>}</section>
 <section id="about" className="about section"><div className="portrait"><Picture src={data.designerPhoto} alt="조명 디자이너 김재준"/><span>BEHIND THE LIGHT</span></div><div className="about-copy"><p className="eyebrow">02 / ABOUT THE DESIGNER</p><h2>이야기에 빛을,<br/>찰나에 생명력을.</h2><p className="about-description">{data.about.description}</p><div className="designer"><h3>{data.about.name}<span>{data.about.englishName}</span></h3><p>{data.about.role}</p>{(data.about.education||[]).map(item=><p key={item}>{item}</p>)}</div><p className="signature">무대 위에서 ‘불(빛)을 하는’ 자, 불한당.</p></div></section>
 <section id="contact" className="contact section"><p className="eyebrow">03 / LET’S CREATE TOGETHER</p><h2>당신의 다음 무대에<br/>함께할 빛.</h2><a className="contact-email" href={`mailto:${data.contact.email}`}>{data.contact.email}<ArrowUpRight/></a><div className="contact-links"><a href={`tel:${data.contact.phone.replace(/\s/g,'')}`}><Phone size={17}/>{data.contact.phone}</a><a href={`https://www.instagram.com/${data.contact.instagram.replace('@','')}/`} target="_blank" rel="noreferrer"><Instagram size={17}/>{data.contact.instagram}</a><a href={`mailto:${data.contact.email}`}><Mail size={17}/>프로젝트 문의</a></div></section></main>
 <footer><span>{data.copyright}</span><a href="#home">BACK TO TOP ↑</a></footer>
 {notice&&<div role="status" className="notice">{notice}<button aria-label="알림 닫기" onClick={()=>setNotice('')}><X size={18}/></button></div>}
 <dialog ref={dialog} className={`project-dialog ${selected&&!selected.images.length?'record-dialog':''}`} onCancel={()=>setSelected(null)} onClick={e=>{if(e.target===dialog.current)setSelected(null);}} onKeyDown={e=>{if(e.key==='ArrowLeft')changeImage(-1);if(e.key==='ArrowRight')changeImage(1);}}>{selected&&<><div className="dialog-top"><span>{selected.year} / {genreLabel(selected.genre)}</span><button autoFocus aria-label="작품 닫기" onClick={()=>setSelected(null)}><X/></button></div>{!!selected.images.length&&<div className="gallery"><Picture src={selected.images[imageIndex]} alt={`${selected.title} — ${imageIndex+1}`}/>{selected.images.length>1&&<><button className="previous" aria-label="이전 사진" onClick={()=>changeImage(-1)}><ChevronLeft/></button><button className="next" aria-label="다음 사진" onClick={()=>changeImage(1)}><ChevronRight/></button><span className="gallery-count">{imageIndex+1} / {selected.images.length}</span></>}</div>}<div className="dialog-info"><h2>{selected.title}</h2><p>{selected.location}</p><p>{selected.role}</p>{selected.description&&<p>{selected.description}</p>}{!selected.images.length&&<p className="archive-note">공연 이력</p>}</div>{selected.images.length>1&&<div className="thumbnails">{selected.images.map((img,i)=><button key={i} aria-label={`${i+1}번 사진`} aria-pressed={imageIndex===i} onClick={()=>setImageIndex(i)}><Picture src={img} alt=""/></button>)}</div>}</>}</dialog></>;
}
