import {useEffect, useMemo, useRef, useState, type ReactNode} from 'react';
import {ArrowUpRight, X, ChevronLeft, ChevronRight, Instagram, Mail, Phone, Search, Download} from 'lucide-react';
import initial from './portfolio.json';
import './portfolio.css';

type Project={id:string;title:string;year:string;genre:string;location?:string;role:string;description?:string;images:string[]};
type Portfolio=typeof initial & {about:typeof initial.about & {businessCardBackground?:string;businessCardPdf?:string}};
const genres=[['All','전체','All'],['Theatre','연극','Theatre'],['Musical','뮤지컬','Musicals'],['Dance','무용','Dance'],['Other','콘서트 및 음악','Concerts & Music']];
const genreLabel=(genre:string)=>genres.find(([g])=>g.toLowerCase()===genre.toLowerCase())?.[1]||'콘서트 및 음악';
const roleLabel=(role:string)=>/programmer/i.test(role)?'Programmer':/designer/i.test(role)?'Designer':role==='Role'||!role.trim()?'포지션 미정':role;
const matchesGenre=(project:Project,genre:string)=>genre==='All'||(genre==='Other'?!['theatre','musical','dance'].includes(project.genre.toLowerCase()):project.genre.toLowerCase()===genre.toLowerCase());
function photoUrl(url:string){const match=url.match(/drive\.google\.com\/(?:file\/d\/([^/?]+)|(?:open|uc)\?[^#]*?id=([^&#]+))/);return match?`https://lh3.googleusercontent.com/d/${match[1]||match[2]}`:url;}
function photoSize(src:string,size:number){const url=photoUrl(src);return /^https:\/\/lh3\.googleusercontent\.com\/d\/[^/?=]+$/.test(url)?`${url}=s${size}`:url;}
function Picture({src,alt,size=640}:{src?:string;alt:string;size?:number}){const [broken,setBroken]=useState(false);useEffect(()=>setBroken(false),[src]);return src&&!broken?<img draggable={false} src={photoSize(src,size)} alt={alt} decoding="async" loading="lazy" referrerPolicy="no-referrer" onError={()=>setBroken(true)}/>:<div className="no-photo"><span>不汗黨</span><small>{src?'사진을 불러올 수 없습니다':'공연 이력'}</small></div>;}
type EditorBridge={data:unknown;active:boolean;select:(id:string)=>void;add:(genre:string,year:string)=>void;text:(path:string,value:string)=>ReactNode};
export default function PortfolioApp({editor}:{editor?:EditorBridge}){
 const storedData:Portfolio=initial;
 const [genre,setGenre]=useState('All'),[query,setQuery]=useState(''),[selected,setSelected]=useState<Project|null>(null),[imageIndex,setImageIndex]=useState(0);
 const data=editor?editor.data as Portfolio:storedData;
 const editable=(path:string,value:string)=>{if(editor?.active)return editor.text(path,value);const style=(data.textStyles as Record<string,{size:number;color:string;opacity:number}>)[path];return style?<span style={{fontSize:style.size,color:/^#(?:f97316|b75e15|ea875d|eb6c05)$/i.test(style.color)?"#21F1A8":style.color,opacity:style.opacity}}>{value}</span>:value;};
 const dialog=useRef<HTMLDialogElement>(null),lastFocus=useRef<HTMLElement|null>(null);

 useEffect(()=>{if(selected){dialog.current?.showModal();document.body.style.overflow='hidden';}else{dialog.current?.close();document.body.style.overflow='';lastFocus.current?.focus();}return()=>{document.body.style.overflow='';};},[selected]);
 const projects=useMemo(()=>data.projects.map(p=>({...p,year:String(p.year||'연도 미정'),genre:p.genre||'',images:(p.images||[]).filter(src=>typeof src==='string'&&src.trim())})).sort((a,b)=>Number(b.year)-Number(a.year)) as Project[],[data.projects]);
 const shown=useMemo(()=>projects.filter(p=>matchesGenre(p,genre)&&`${p.title} ${p.year} ${p.location||''}`.toLowerCase().includes(query.toLowerCase())),[projects,genre,query]);
 const groups=useMemo(()=>{const years=new Map<string,{year:string;works:Project[];photos:Project[];records:Project[]}>();for(const project of shown){let group=years.get(project.year);if(!group){group={year:project.year,works:[],photos:[],records:[]};years.set(project.year,group);}group.works.push(project);(project.images.length?group.photos:group.records).push(project);}return [...years.values()];},[shown]);
 const counts=useMemo(()=>Object.fromEntries(genres.map(([key])=>[key,projects.filter(p=>matchesGenre(p,key)).length])),[projects]);
 const open=(p:Project)=>{if(editor?.active){editor.select(p.id);return;}lastFocus.current=document.activeElement as HTMLElement;setImageIndex(0);setSelected(p);};
 const changeImage=(step:number)=>{if(selected?.images.length)setImageIndex(i=>(i+step+selected.images.length)%selected.images.length);};
 return <div className="portfolio-view spring-theme" onContextMenu={e=>{if(e.target instanceof HTMLImageElement)e.preventDefault();}} onDragStart={e=>{if(e.target instanceof HTMLImageElement)e.preventDefault();}} style={{fontFamily:data.fonts.sans}}><header><a className="brand" href="#home">불한당<span>LIGHTING DESIGN STUDIO</span></a><nav aria-label="주 메뉴"><a href="#work">WORK</a><a href="#about">ABOUT</a><a href="#contact">CONTACT</a></nav>{import.meta.env.DEV&&!editor?<a className="local-editor-link" href="/?editor=1">편집</a>:<span className="header-note">SEOUL, KR</span>}</header>
 <main><section className="hero" id="home"><div className="hero-light"/><div className="hero-top"><span>{editable("heroSub",data.heroSub||"Stage Lighting Design")}</span><span>빛으로 만드는, 극의 공간</span></div><div className="hero-title">{data.logoUrl?<img src={photoUrl(data.logoUrl)} alt="불한당 스튜디오 원본 로고" referrerPolicy="no-referrer"/>:<h1>불한당</h1>}</div><div className="hero-bottom"><div><p className="eyebrow section-label">Intro</p><div className="hero-quote">{editable('intro.quote',data.intro.quote)}</div></div><div className="hero-description">{editable('intro.description',data.intro.description)}</div></div></section>
 <section id="work" className="work section"><div className="section-label-row"><p className="eyebrow section-label">01 / Works</p></div><div className="work-toolbar"><div className="filters" aria-label="장르 필터">{genres.map(([key,label,english])=><button key={key} aria-pressed={genre===key} className={genre===key?'active':''} onClick={()=>setGenre(key)}><span className="filter-english">{english}</span><span>{label}<small>{counts[key]}</small></span></button>)}</div><label className="search"><Search size={16}/><input aria-label="작품 검색" placeholder="작품명 · 연도 검색" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
 <div className="year-archive" key={`${genre}:${query}`}><span className="sr-only" role="status">{shown.length}개 작품 · {groups.length}개 연도</span>{groups.map(({year,works,photos,records})=>{return <details className="year-group" key={year} open><summary><span className="year-label">{year}<small>{works.length}개 작품</small></span><span className="year-toggle" aria-hidden="true"/></summary><div className="year-content">{!!photos.length&&<div className="year-photo-grid">{photos.map(p=><button className="photo-project" key={p.id} onClick={()=>open(p)}><div className="project-image"><Picture src={p.images[0]} alt={p.title}/><span className="project-open">작품 보기 <ArrowUpRight size={17}/></span></div><div className="photo-project-copy"><div className="project-meta"><span>{genreLabel(p.genre)} / LIGHTING DESIGN</span><span>{p.year}</span></div><h3>{p.title}</h3><p>{p.location||p.role}</p></div></button>)}</div>}{!!records.length&&<div className="year-records">{records.map(p=><button className="record-project" key={p.id} onClick={()=>open(p)}><span className="record-genre">{genreLabel(p.genre)}</span><span className="record-role">{roleLabel(p.role)}</span><span className="record-copy"><strong>{p.title}</strong><span>{p.location||p.role}</span></span></button>)}</div>}{editor?.active&&<button type="button" className="year-add-project" aria-label={`${year}년 공연 추가하기`} onClick={()=>editor.add(genre==='All'?'Theatre':genre,year)}>＋ 공연 추가하기</button>}</div></details>;})}</div>
 {!shown.length&&<div className="empty">검색된 작품이 없습니다.<button onClick={()=>{setQuery('');setGenre('All');}}>전체 작품 보기</button></div>}</section>
 <section id="about" className="about section">{data.about.businessCardBackground&&<div className="business-card-background" aria-hidden="true" style={{backgroundImage:`url(${photoUrl(data.about.businessCardBackground)})`}}/>}<div className="section-label-row"><p className="eyebrow section-label">02 / About Designer</p></div><div className="about-copy"><div className="designer-role">{editable('about.role',data.about.role)}</div><h2 className="designer-name">{editable('about.name',data.about.name)}<span>{editable('about.englishName',data.about.englishName||'')}</span></h2><div className="designer-education">{(data.about.education||[]).map((item,index)=><div key={index}>{editable('about.education.'+index,item)}</div>)}</div></div><div className="about-description">{editable('about.description',data.about.description)}</div><div className="business-card-download">{data.about.businessCardPdf?<a href={data.about.businessCardPdf} download="불한당명함_김재준.pdf"><Download size={17}/>명함 PDF 다운로드</a>:<button type="button" disabled><Download size={17}/>명함 PDF 다운로드<span>준비 중</span></button>}{data.about.businessCardPdf&&<a href="/business-card.jpg" download="불한당명함_김재준.jpg"><Download size={17}/>명함 JPG 다운로드</a>}</div></section>
 <section id="contact" className="contact section"><div className="section-label-row"><p className="eyebrow section-label">03 / Contact</p></div><div className="contact-links"><a className="contact-card" href={editor?.active?undefined:`tel:${data.contact.phone.replace(/\s/g,'')}`}><Phone size={20}/><div>{editable('contact.phone',data.contact.phone)}</div></a><a className="contact-card" href={editor?.active?undefined:`https://www.instagram.com/${data.contact.instagram.replace('@','')}/`} target="_blank" rel="noreferrer"><Instagram size={20}/><div>{editable('contact.instagram',data.contact.instagram)}</div></a><a className="contact-card" href={editor?.active?undefined:`mailto:${data.contact.email}`} aria-label={editor?.active?undefined:`${data.contact.email} 메일 보내기`}><Mail size={20}/><div>{editable('contact.email',data.contact.email)}</div></a></div></section></main>
 <footer><span>{data.copyright}</span><a href="#home">BACK TO TOP ↑</a></footer>

 <dialog ref={dialog} className={`project-dialog ${selected&&!selected.images.length?'record-dialog':''}`} onCancel={()=>setSelected(null)} onClick={e=>{if(e.target===dialog.current)setSelected(null);}} onKeyDown={e=>{if(e.key==='ArrowLeft')changeImage(-1);if(e.key==='ArrowRight')changeImage(1);}}>{selected&&<><div className="dialog-top"><span>{selected.year} / {genreLabel(selected.genre)}</span><button autoFocus aria-label="작품 닫기" onClick={()=>setSelected(null)}><X/></button></div>{!!selected.images.length&&<div className="gallery"><Picture src={selected.images[imageIndex]} alt={`${selected.title} — ${imageIndex+1}`} size={1600}/>{selected.images.length>1&&<><button className="previous" aria-label="이전 사진" onClick={()=>changeImage(-1)}><ChevronLeft/></button><button className="next" aria-label="다음 사진" onClick={()=>changeImage(1)}><ChevronRight/></button><span className="gallery-count">{imageIndex+1} / {selected.images.length}</span></>}</div>}<div className="dialog-info"><h2>{selected.title}</h2><p>{selected.location}</p><p>{selected.role}</p>{selected.description&&<p>{selected.description}</p>}{!selected.images.length&&<p className="archive-note">공연 이력</p>}</div>{selected.images.length>1&&<div className="thumbnails">{selected.images.map((img,i)=><button key={i} aria-label={`${i+1}번 사진`} aria-pressed={imageIndex===i} onClick={()=>setImageIndex(i)}><Picture src={img} alt="" size={160}/></button>)}</div>}</>}</dialog></div>;
}
